# config/config.yaml

app:
  intervalo_scraping_minutos: 240
  database_path: "data/anuncios.db"
  
score:
  pesos:
    preco: 0.4
    km: 0.2
    ano: 0.1
    fipe: 0.3


fipe:
  dias_cache: 15

# Nova estrutura: Lista de locais para o robô varrer
localizacoes:
  - estado: "ba"
    regiao: "salvador"

filtros_globais:
  motor_minimo: "1.2"
  km_minimo_global: 5000            # Ignora carros com KM suspeitamente baixa
  km_maximo_global: 50000          # Carros acima disso nem entram no score
  km_ano_maximo: 12000             # Média de Salvador é alta, mas 16k é o limite
  ano_minimo: 2018                 # Carros mais velhos que 2019 perdem muito score
  preco_maximo: 115000              # Seu teto orçamentário
  fipe_alerta_abaixo_de_percentual: 88
  fipe_oportunidade_ate_percentual: 98

veiculos:
  - marca: "toyota"
    modelo: "yaris"
    preco_maximo: 105000
    versoes_aceitas: ["xs", "xls"]
    categoria: "hatch" # Ou sedan, dependendo do que você busca

  - marca: "honda"
    modelo: "city"
    categoria: "hatch" 
    preco_maximo: 105000 
    versoes_aceitas: ["todas"]

  - marca: "honda"
    modelo: "fit"
    categoria: "hatch" 
    preco_maximo: 85000 
    versoes_aceitas: ["todas"]

  - marca: "nissan"
    modelo: "kicks"
    preco_maximo: 115000
    categoria: "suv"
    versoes_aceitas: ["advance", "exclusive"]

  - marca: "honda"
    modelo: "wr-v"
    preco_maximo: 105000 
    categoria: "suv"
    versoes_aceitas: ["ex", "exl"]

  - marca: "toyota"
    modelo: "corolla"
    preco_maximo: 115000 
    versoes_aceitas: ["todas"]